Repository jknack/handlebars.java, pull requests merged in 2018-05, with the labels that each got.

#548 Fix formatters not being evaluated a second time
  handlebars/src/main/java/com/github/jknack/handlebars/internal/FormatterChain.java
  handlebars/src/test/java/com/github/jknack/handlebars/FormatterTest.java
Labels: bug

#618 PathCompiler string literal pattern fails if literal contains leading /
  handlebars/src/main/java/com/github/jknack/handlebars/PathCompiler.java
  handlebars/src/test/java/com/github/jknack/handlebars/PropertyPathParserTest.java
Labels: enhancement

#620 Render blocks in the parent context and assure a block is passed to templates that use @partial-block
  handlebars/src/main/java/com/github/jknack/handlebars/Context.java
  handlebars/src/main/java/com/github/jknack/handlebars/Handlebars.java
  handlebars/src/main/java/com/github/jknack/handlebars/internal/Partial.java
  handlebars/src/main/java/com/github/jknack/handlebars/internal/PartialBlockForwardingTemplate.java
  handlebars/src/test/java/com/github/jknack/handlebars/LazyPartialBlockEvaluationTest.java
  handlebars/src/test/java/com/github/jknack/handlebars/PartialBlockTest.java
Labels: enhancement

#582 fixing docs for capitalizeFirst
  handlebars/src/main/java/com/github/jknack/handlebars/helper/StringHelpers.java
Labels: documentation

#565 Fixing tiny documentation issue with upper function
  handlebars/src/main/java/com/github/jknack/handlebars/helper/StringHelpers.java
Labels: documentation

#510 Link to javadoc added
  README.md
Labels: documentation

#628 use diamond operator
  handlebars/src/main/java/com/github/jknack/handlebars/Context.java
  handlebars/src/main/java/com/github/jknack/handlebars/Handlebars.java
  handlebars/src/main/java/com/github/jknack/handlebars/cache/HighConcurrencyTemplateCache.java
  handlebars/src/main/java/com/github/jknack/handlebars/context/FieldValueResolver.java
  handlebars/src/main/java/com/github/jknack/handlebars/context/MemberValueResolver.java
  handlebars/src/main/java/com/github/jknack/handlebars/context/MethodValueResolver.java
  handlebars/src/main/java/com/github/jknack/handlebars/helper/BlockHelper.java
  handlebars/src/main/java/com/github/jknack/handlebars/helper/DefaultHelperRegistry.java
  handlebars/src/main/java/com/github/jknack/handlebars/helper/I18nHelper.java
  handlebars/src/main/java/com/github/jknack/handlebars/internal/BaseTemplate.java
  handlebars/src/main/java/com/github/jknack/handlebars/internal/Block.java
  handlebars/src/main/java/com/github/jknack/handlebars/internal/HelperResolver.java
  handlebars/src/main/java/com/github/jknack/handlebars/internal/MustacheSpec.java
  handlebars/src/main/java/com/github/jknack/handlebars/internal/Partial.java
  handlebars/src/main/java/com/github/jknack/handlebars/internal/TemplateBuilder.java
  handlebars/src/main/java/com/github/jknack/handlebars/internal/TemplateList.java
  handlebars/src/main/java/com/github/jknack/handlebars/internal/WhiteSpaceControl.java
  handlebars/src/main/java/com/github/jknack/handlebars/internal/js/RhinoHandlebars.java
  handlebars/src/test/java/com/github/jknack/handlebars/ContextTest.java
  handlebars/src/test/java/com/github/jknack/handlebars/DecoratorTest.java
  handlebars/src/test/java/com/github/jknack/handlebars/EachKeyTest.java
  handlebars/src/test/java/com/github/jknack/handlebars/MustacheTest.java
  handlebars/src/test/java/com/github/jknack/handlebars/PropertyAccessTest.java
  handlebars/src/test/java/com/github/jknack/handlebars/PseudoVarsTest.java
  handlebars/src/test/java/com/github/jknack/handlebars/ScalarContextTest.java
  handlebars/src/test/java/com/github/jknack/handlebars/TagTypeTest.java
  handlebars/src/test/java/com/github/jknack/handlebars/ValueResolverTest.java
  handlebars/src/test/java/com/github/jknack/handlebars/bench/CompilationPerSecondBenchTest.java
  handlebars/src/test/java/com/github/jknack/handlebars/bench/Stock.java
  handlebars/src/test/java/com/github/jknack/handlebars/cache/ConcurrentMapTemplateCacheTest.java
  handlebars/src/test/java/com/github/jknack/handlebars/cache/HighConcurrencyTemplateCacheTest.java
  handlebars/src/test/java/com/github/jknack/handlebars/custom/Blog.java
  handlebars/src/test/java/com/github/jknack/handlebars/i177/Issue177.java
  handlebars/src/test/java/com/github/jknack/handlebars/i237/Issue237.java
  handlebars/src/test/java/com/github/jknack/handlebars/internal/TemplateTest.java
  handlebars/src/test/java/com/github/jknack/handlebars/io/ServletContextTemplateLoaderTest.java
  handlebars/src/test/java/com/github/jknack/handlebars/issues/Issue476.java
  handlebars/src/test/java/mustache/specs/SpecTest.java
Labels: enhancement

#629 fix typo
  handlebars/src/main/java/com/github/jknack/handlebars/Options.java
Labels: documentation
