Repository jknack/handlebars.java, pull requests merged in 2021-09, with the labels that each got.

#855 Upgrade to latest handlebars.js (4.7.7)
  handlebars-maven-plugin/src/main/java/com/github/jknack/handlebars/maven/PrecompilePlugin.java
  handlebars-maven-plugin/src/test/java/com/github/jknack/handlebars/maven/Issue234.java
  handlebars-maven-plugin/src/test/java/com/github/jknack/handlebars/maven/PrecompilePluginTest.java
  handlebars-springmvc/src/main/java/com/github/jknack/handlebars/springmvc/HandlebarsViewResolver.java
  handlebars/src/main/java/com/github/jknack/handlebars/Handlebars.java
  handlebars/src/main/resources/handlebars-v4.7.7.js
  handlebars/src/test/java/com/github/jknack/handlebars/i417/Issue417.java
Labels: handlebars.js

#845 Update README.md
  README.md
Labels: documentation

#866 Add Instant support for dateFormat
  handlebars/src/main/java/com/github/jknack/handlebars/helper/StringHelpers.java
  handlebars/src/test/java/com/github/jknack/handlebars/DateFormatTest.java
Labels: enhancement

#849 Added support for newlines in string literals
  handlebars/src/main/antlr4/com/github/jknack/handlebars/internal/HbsLexer.g4
  handlebars/src/test/java/handlebarsjs/spec/StringLiteralParametersTest.java
Labels: enhancement

#824 ISSUE-823: Fix token position when text block has new line char
  handlebars/src/main/antlr4/com/github/jknack/handlebars/internal/HbsLexer.g4
  handlebars/src/test/java/com/github/jknack/handlebars/internal/Issue823.java
Labels: enhancement

#830 Add @HelperFunction annotation for overriding method names from Helper Sources (#829)
  handlebars/src/main/java/com/github/jknack/handlebars/helper/DefaultHelperRegistry.java
  handlebars/src/main/java/com/github/jknack/handlebars/helper/HelperFunction.java
  handlebars/src/test/java/com/github/jknack/handlebars/ReflectiveHelperTest.java
Labels: enhancement
